installation_and_upgrade/ibex_install_utils/install_tasks.py
Upgrade config and sql schema on deploy latest
https://github.com/ISISComputingGroup/IBEX/issues/2848
=> Upgrade config as part of install latest

developer_support_script/build_dependencies.py
=> Add build dependency generator

installation_and_upgrade/IBEX_upgrade.py, installation_and_upgrade/ibex_install_utils/install_tasks.py
Allow install for E4 client (and removal of)
=> Install for E4 client

installation_and_upgrade/calibration_files_updater.py, installation_and_upgrade/calibration_files_updater/calibration_files_updater.py
Add a script for updating calibration files across with master across all instruments.
https://github.com/ISISComputingGroup/IBEX/issues/3016
Maps a drive to the network location from each inst then do a git pull if appropriate. I used ALF for testing the Git workflow.
Make sure that files added by git pull under the admin account are editable on non-admin account.
=> Ticket3016 add script to update calibrations

installation_and_upgrade/ibex_install_utils/install_tasks.py
Added resources check for RAM and free disk space using `psutil` package in python.
- Checks for 30GB of free space and 8GB of RAM on install.
- Checks for 8GB of RAM on upgrade.
=> Ticket3194 ibex mini servers resource checks

installation_and_upgrade/ibex_install_utils/install_tasks.py
Add step to put the autostart into the PC autostart folder
https://github.com/ISISComputingGroup/IBEX/issues/1315
=> Add task to put ibex start script in autostart area

installation_and_upgrade/ibex_install_utils/install_tasks.py
https://github.com/ISISComputingGroup/IBEX/issues/3609
=> Add nicos release file if it doesn't exist

installation_and_upgrade/ibex_install_utils/install_tasks.py, installation_and_upgrade/instrument_install.bat, installation_and_upgrade/training_update.bat
Changes that were made in order for the deploy to work
=> Changes made for deploy

installation_and_upgrade/ibex_install_utils/install_tasks.py
This will now be done as part of a build.
See https://github.com/ISISComputingGroup/IBEX/issues/3762
=> Ticket 3762: Removed code that adds NICOS release file

installation_and_upgrade/IBEX_upgrade.py
Also added install_latest_incr
See ISISComputingGroup/IBEX#3836
=> install_latest takes latest clean build

installation_and_upgrade/IBEX_upgrade.py, installation_and_upgrade/ibex_install_utils/admin_runner.py, installation_and_upgrade/ibex_install_utils/install_tasks.py, installation_and_upgrade/instrument_deploy.bat, installation_and_upgrade/upgrade_mysql.bat
Upgrade script to upgrade instruments to MYSQL8
https://github.com/ISISComputingGroup/IBEX/issues/4135
=> Ticket4135

installation_and_upgrade/define_latest_genie_python.bat, installation_and_upgrade/ibex_install_utils/file_utils.py, installation_and_upgrade/ibex_install_utils/install_tasks.py, installation_and_upgrade/ibex_install_utils/run_process.py, installation_and_upgrade/instrument_deploy.bat, installation_and_upgrade/instrument_install.bat
Also tries to set path for Python to allow easier installation
=> Dump sql data and reload

installation_and_upgrade/ibex_install_utils/install_tasks.py
As per https://github.com/ISISComputingGroup/IBEX/issues/3860 , add a prompt to the upgrade script directing developers to the appropriate instructions for upgrading RAM on instrument machines as part of the deployment script.
=> Ticket3860 upgrade ram on instruments

installation_and_upgrade/ibex_install_utils/install_tasks.py
Add prompts to upgrade script for https://github.com/ISISComputingGroup/IBEX/issues/4214
=> add install task to hide treesize

installation_and_upgrade/ibex_install_utils/install_tasks.py
Add autorestart for MYSQL service in deploy script
For https://github.com/ISISComputingGroup/IBEX/issues/4444
=> Add autorestart for mysql

installation_and_upgrade/ibex_install_utils/install_tasks.py, installation_and_upgrade/instrument_deploy.bat, repo-tool/scripts/proposal_printing.py
Put my config install all in one task.
Note that journal table is done as part of config_my_sql.
Sorry I put the update to the tickets thing in. This need to be remembered for the future but can probably now be deleted as a script.
=> Tidy mysql install

repo-tool/scripts/proposal_printing.py
Change the script for ticket prioritisation. This is probably no longer needed, but I would like to capture the changes.
=> Ticket prioritisation update

installation_and_upgrade/ibex_install_utils/file_utils.py
Fix directory creation logic, which would fail if a directory was left over from an aborted previous run
=> Fix empty directory creation

installation_and_upgrade/ibex_install_utils/install_tasks.py
https://github.com/ISISComputingGroup/IBEX/issues/4255
Update process on dev machine:
- Run services.msc as admin
- Stop Mysql service
- Delete `C:\instrument\apps\mysql`
- Copy version from `\\isis\inst$\Kits$\CompGroup\ICP\MySQL` locally
- Unzip it and move it to the same location as the old one (the path to `mysql.exe` should be `C:\instrument\apps\mysql\bin\mysql.exe`
=> MySQL 8.0.15 -> 8.0.17

workflow_support_scripts/make_ioc.bat, workflow_support_scripts/make_test_ioc.bat
Added a script to make an ioc in one command by passing the names of the folders in the support and ioc or the ISIS folder.
Added a script to make an ioc and test it.
=> Added make_ioc and make_test_ioc scripts

installation_and_upgrade/IBEX_upgrade.py, installation_and_upgrade/define_latest_genie_python.bat, installation_and_upgrade/ibex_install_utils/install_tasks.py
Install genie python 3
- Also tidy up install types.
For https://github.com/ISISComputingGroup/IBEX/issues/5050
=> Ticket4841 install genie python 3

installation_and_upgrade/IBEX_upgrade.py, installation_and_upgrade/ibex_install_utils/exceptions.py, installation_and_upgrade/ibex_install_utils/install_tasks.py
Add `-` to make path `BUILD-XXX` for genie_python 3 install.
Make exception show problem not just name
Show install path for genie python 3
=> Fix install

installation_and_upgrade/ibex_install_utils/install_tasks.py
Install latests version on mysql without destroying the current database
=> Install latest mysql

installation_and_upgrade/Jenkinsfile
Add timestamp printing of jenkins output
=> Add timestamps to jenkins output

installation_and_upgrade/ibex_install_utils/install_tasks.py
See https://github.com/ISISComputingGroup/IBEX/issues/5196
=> Ticket 5196: Added step to confirm instrument name

installation_and_upgrade/developer_update.bat, installation_and_upgrade/ibex_install_utils/install_tasks.py
Ticket:
https://github.com/ISISComputingGroup/IBEX/issues/5152
=> added new developer script

installation_and_upgrade/ibex_install_utils/install_tasks.py
Script definitions may need to be updated on deploy. Add a step to check and do it if needed.
=> Added step to update script definitions

installation_and_upgrade/ibex_install_utils/file_utils.py
Use /MT flag on robocopy delete
=> Use /MT for delete

installation_and_upgrade/ibex_install_utils/install_tasks.py
Adds an upgrade step to change shortcuts to genie_python to python 3 directory
https://github.com/ISISComputingGroup/IBEX/issues/5175
=> Add upgrade step to change user shortcuts

installation_and_upgrade/ibex_install_utils/ca_utils.py, installation_and_upgrade/ibex_install_utils/install_tasks.py
Don't fix shortcuts when doing auto install 
Stop install loading instrument scripts
=> Fix auto install

installation_and_upgrade/ibex_install_utils/install_tasks.py
See https://github.com/ISISComputingGroup/IBEX/issues/5164
=> Ticket 5164: Added explicit check for MUONFE fix

installation_and_upgrade/ibex_install_utils/file_utils.py
Retry delete - may or may not help...
=> Retry delete

installation_and_upgrade/ibex_install_utils/admin_runner.py, installation_and_upgrade/ibex_install_utils/ca_utils.py, installation_and_upgrade/ibex_install_utils/file_utils.py, installation_and_upgrade/ibex_install_utils/install_tasks.py
For https://github.com/ISISComputingGroup/IBEX/issues/5176
=> Ticket5176

installation_and_upgrade/ibex_install_utils/install_tasks.py
Set failureflag - otherwise it may not restart if it exits with an error
See ISISComputingGroup/IBEX#5327
=> Ticket5327 mysql error stop

build_tools/purge_archive.py
=> Add missing dirs

installation_and_upgrade/IBEX_upgrade.py, installation_and_upgrade/ibex_install_utils/install_tasks.py
https://github.com/ISISComputingGroup/IBEX/issues/5353
Added an email template to send to instrument scientists with release notes.
=> Added email template to prompt to email scientists

build_tools/purge_archive.py
Purge old script_generator builds
=> Purge old script_generator builds

installation_and_upgrade/instrument_install_latest_build_only.bat
=> Add PYTHONUNBUFFERED

build_tools/purge_archive.bat
Add purge of debug symbols directory
=> Add purge of symbols

installation_and_upgrade/ibex_install_utils/ca_utils.py, installation_and_upgrade/ibex_install_utils/install_tasks.py, installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
Set alerts URL and password as part of deploy
=> Add step to set alert url and password

installation_and_upgrade/ibex_install_utils/install_tasks.py, installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
=> Fix deploy; can't register ICP in non-interactive deploy

installation_and_upgrade/ibex_install_utils/tasks/mysql_tasks.py
Test using `developer_update.bat`
For https://github.com/ISISComputingGroup/IBEX/issues/5815
=> Use decode to convert bytes to unicode

workflow_support_scripts/convert_temp_calib_files.py, workflow_support_scripts/opi_diff.bat
https://github.com/ISISComputingGroup/IBEX/issues/5850
To test:
- Grab and unzip (into their own folder) zip file from RhFe sensor email on ISIS Experiment Controls mailbox
- Run `%PYTHON3% convert_temp_calib_files.py -i <folder where you unzipped files to> -o <output folder>`
- Check output values match dat file
- Check output format matches other FXXX.txt files on C:\Instrument\Settings\config\common\temp_sensors
=> Add RhFe sensor converter

installation_and_upgrade/ibex_install_utils/install_tasks.py, installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py, installation_and_upgrade/ibex_install_utils/tasks/vhd_tasks.py
- Only try to move the generic inst file if it actually exists
- Double check that mysql is stopped before attempting vhd dismount
=> Fix create vhd

installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
Remove Muonfe isisicp patch, see ISISComputingGroup/IBEX#5845
=> Remove muonfe isisicp patch

installation_and_upgrade/define_latest_genie_python.bat, installation_and_upgrade/instrument_deploy.bat, installation_and_upgrade/instrument_install.bat, installation_and_upgrade/instrument_install_latest_build_only.bat, installation_and_upgrade/instrument_update.bat
See ISISComputingGroup/IBEX#5914
=> Fix install python check

installation_and_upgrade/instrument_deploy.bat
Fix quoting on SET - see ISISComputingGroup/IBEX#5913
=> Fix quoting

installation_and_upgrade/Jenkinsfile_vhd_creation, installation_and_upgrade/ibex_install_utils/admin_runner.py, installation_and_upgrade/ibex_install_utils/install_tasks.py, installation_and_upgrade/ibex_install_utils/tasks/vhd_tasks.py, installation_and_upgrade/vhd_build_force_cleanup.bat
For https://github.com/ISISComputingGroup/IBEX/issues/6110
- Add cleanup hook in Jenkins
- Clean up a bit more aggressively in situations where an extra log file gets created after dismounting the vhd but before restoring the backup
- Improve logging/diagnostics so that we can diagnose future problems more easily
=> Ticket6110 vhds

installation_and_upgrade/ibex_install_utils/tasks/mysql_tasks.py
Updated MYSQL version
Ticket: https://github.com/ISISComputingGroup/IBEX/issues/6370
=> MYSQL version update

installation_and_upgrade/ibex_install_utils/install_tasks.py, installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py, installation_and_upgrade/instrument_install_latest_build_only.bat
prompt to select galil driver to run by default post install
=> Select galil driver

installation_and_upgrade/ibex_install_utils/install_tasks.py, installation_and_upgrade/ibex_install_utils/tasks/common_paths.py, installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py, installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
https://github.com/ISISComputingGroup/IBEX/issues/6814
=> Install correct galil driver

installation_and_upgrade/ibex_install_utils/install_tasks.py, installation_and_upgrade/ibex_install_utils/tasks/mysql_tasks.py, installation_and_upgrade/vhd_post_install.bat
Additions for deploying VHD build on real system
See ISISComputingGroup/IBEX#6806 and  ISISComputingGroup/IBEX#6124
=> Add post install vhd tasks

installation_and_upgrade/ibex_install_utils/run_process.py, installation_and_upgrade/ibex_install_utils/tasks/client_tasks.py
See ISISComputingGroup/IBEX#6991
=> Trap errors better on client install

installation_and_upgrade/instrument_save_settings.bat
Add script to call pre-deploy task
=> Add save settings script

installation_and_upgrade/IBEX_upgrade.py
https://github.com/ISISComputingGroup/IBEX/issues/7250
=> Ticket7250 fix partial release install

installation_and_upgrade/ibex_install_utils/admin_runner.py, installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
Runs the git update step as admin if it is installed in program files, otherwise run as normal user.
=> Run git update as admin if needed

installation_and_upgrade/ibex_install_utils/tasks/backup_tasks.py
skip backup of labview modules in settings
=> Ignore labview modules on backup of Settings

installation_and_upgrade/ibex_install_utils/install_tasks.py
Disable adding autostart script
Will fix it in ISISComputingGroup/IBEX#7589
=> Disable prompt for autostart script

SECI_Config_Analyser/Directory_Operations.py, SECI_Config_Analyser/SECI_Config_Analyser.py
Used in preparation for PEARL migration.  Discovered script had errors and untidy output.
=> Fix errors, tidy formatting

installation_and_upgrade/instrument_deploy.bat
Removed the previous admin check which allowed users to carry on whilst logged in as admin, to a admin check that will exit if detected.
=> added admin check to bat file

release_scripts/Jenkinsfile_branches, release_scripts/branches.py, release_scripts/requirements.txt
https://github.com/ISISComputingGroup/IBEX/issues/6973
The script creates all the release branches and writes the versions in all relevant places. See the wiki changes for more info.
To test run the Jenkins pipeline `Release_branches`.
=> Ticket6973

installation_and_upgrade/ibex_install_utils/file_utils.py, installation_and_upgrade/ibex_install_utils/install_tasks.py, installation_and_upgrade/ibex_install_utils/tasks/backup_tasks.py, installation_and_upgrade/ibex_install_utils/tasks/common_paths.py, installation_and_upgrade/ibex_install_utils/tasks/git_tasks.py, installation_and_upgrade/ibex_install_utils/tasks/mysql_tasks.py, installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py, installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py, installation_and_upgrade/ibex_install_utils/version_check.py
Link to ticket: https://github.com/ISISComputingGroup/IBEX/issues/7987
=> Ticket7987-upgrade-script-make-better

installation_and_upgrade/ibex_install_utils/file_utils.py
Changed robocopy copy to be robocopy move. 
[8081](https://github.com/ISISComputingGroup/IBEX/issues/8081)
=> Ticket8081_robocopy-copy_changed_to_robocopy-move

installation_and_upgrade/instrument_deploy.bat
Batch file had some changes in to test a local version of genie_python however they are not meant to be on master.
Noticed while doing scanning deploy files for another reason.
=> Update instrument_deploy.bat to not have local test changes

installation_and_upgrade/ibex_install_utils/install_tasks.py, installation_and_upgrade/ibex_install_utils/tasks/git_tasks.py, installation_and_upgrade/instrument_deploy.bat
After ibex installed it will now swap branch to a instrument branch of the release repo.
[Ticket](https://github.com/ISISComputingGroup/IBEX/issues/8057)
=> Ticket8054_add_to_deploy_script_instrument_release_branch

installation_and_upgrade/ibex_install_utils/install_tasks.py, installation_and_upgrade/ibex_install_utils/tasks/git_tasks.py
[Ticket](https://github.com/ISISComputingGroup/IBEX/issues/8134)
=> Ticket8134_changes_to_hotfix_branch_switch_in_deploy

build_tools/JenkinsfileCheckRecentBuilds, build_tools/parse_rules
[Ticket](https://github.com/ISISComputingGroup/IBEX/issues/8123)
=> Add parse_rules and post build action to Jenkins job

installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
If git fetch error, do a gc and prune and then try again
See ISISComputingGroup/IBEX#8162
=> gc and prune if error

installation_and_upgrade/ibex_install_utils/install_tasks.py, installation_and_upgrade/ibex_install_utils/tasks/python_tasks.py
Added upgrade step to delete inst script hooks
=> Add step to remove inst script hook

installation_and_upgrade/ibex_install_utils/tasks/backup_tasks.py
Add a general ignore list to all backup directories
=> Ignore some dirs in backup

installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
Fix typo in return code. Not sure of adding realpath() fixes issue or not, it seems it is getting "progra~1" rather than "program files" in some cases
See ISISComputingGroup/IBEX#8203
=> Fix git path issue

installation_and_upgrade/ibex_install_utils/run_process.py, installation_and_upgrade/ibex_install_utils/tasks/mysql_tasks.py
https://github.com/ISISComputingGroup/IBEX/issues/8236
=> Show progress while backing up database

installation_and_upgrade/ibex_install_utils/install_tasks.py, installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
https://github.com/ISISComputingGroup/IBEX/issues/8360
=> Add log rotation scheduled task

installation_and_upgrade/ibex_install_utils/install_tasks.py, installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py, installation_and_upgrade/update_icp.bat
Add bat to update isisicp separately to an ibex install
after merge, go to `ibex_utils` directory in  `shares\isis_experiment_controls_public` and do a `git pull`
=> add standalone isisicp installer

.github/workflows/lint-and-test-nightly.yml, .github/workflows/push_event_workflow.yml
=> nightly CI

build_tools/purge_archive.py
=> Keep less builds on kits$

build_tools/purge_archive.py
=> Purge win11 client build

installation_and_upgrade/ibex_install_utils/admin_runner.py, installation_and_upgrade/ibex_install_utils/tasks/mysql_tasks.py
https://github.com/ISISComputingGroup/IBEX/issues/8597
=> Ticket 8597

installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
happy to approach this differently, looking to achieve:
- working links
- referencing two sets of release notes
=> update link, recognise we are deploying two versions at a time now

installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
Closes #275 
tested by modifying save_motor_params.bat and making it just call this one step
=> headlessly install java

installation_and_upgrade/ibex_install_utils/install_tasks.py, installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py, installation_and_upgrade/requirements.txt
Because we may now/soon have tools using this, so devs should probably have it installed.
=> install rust
