ISISComputingGroup/ibex_utils

installation_and_upgrade/ibex_install_utils/install_tasks.py

I've added a step in the instrument upgrade script to incorporate changes to the master configurations branch into the instrument configuration
https://github.com/ISISComputingGroup/IBEX/issues/2692
When doing an instrument update, the script attempts to upgrade the configuration from master. If it fails, the user is prompted to complete the steps manually.
The steps performed by the script should be appropriate for the stated task.

Merge from master configurations directory during upgrade

---

installation_and_upgrade/ibex_install_utils/file_utils.py
installation_and_upgrade/ibex_install_utils/install_tasks.py

A fresh install of IBEX will now delete SECI 1 directory "c\Program Files (x86)\CCLRC ISIS Facility".
To test, create that directory, fill with files/directories and run "C:\Instrument\Dev\ibex_utils\installation_and_upgrade\instrument_install.bat".
You will need to have both admin rights to your machine and access rights to "\\isis\inst$\Kits$\C
KeyboardInterrupty_dir_for_robocopy".
Select Y when asked if you want to remove SECI 1, then make sure it has been deleted.

Remove SECI 1 on install.

---

installation_and_upgrade/ibex_install_utils/motor_params.py

This commit catches a ZeroDivisionError exception. Instead of crashing the corresponding value is set to None.
See https://github.com/ISISComputingGroup/IBEX/issues/3500

Catch ZeroDivisionError

---

installation_and_upgrade/ibex_install_utils/install_tasks.py

Changed the `setup_calibrations_repository` upgrade step, such that
1. It raises an error in case of the `git clone` failing. This raises the visibility of the failure as it prompts a user response to retry, skip or abort.
1. It creates the `common` folder as part of the git instruction. When the `git clone` failed previously, the directory would still be created. This would then lead to the install script skipping to trying (and failing) to update the directory in any subsequent run.
1. Fixed syntax in a call to `prompt`.
Issue: https://github.com/ISISComputingGroup/IBEX/issues/3722

Create dir and clone in one step, raise error in case of failure

---

installation_and_upgrade/ibex_install_utils/install_tasks.py
installation_and_upgrade/ibex_install_utils/kafka_utils.py

See https://github.com/ISISComputingGroup/IBEX/issues/4347
Requires https://github.com/ISISComputingGroup/genie_python/pull/164
To test:
```
from ibex_install_utils.kafka_utils import get_existing_topics, add_required_topics
get_existing_topics("tenten.isis.cclrc.ac.uk:9092")
```
Confirm that your instrument isn't in there.
Run `add_required_topics("tenten.isis.cclrc.ac.uk:9092", "YOUR_INST")` and the above again to confirm your instrument is now in the list.

Ticket 4347: Added installation step to update kafka topics

---

installation_and_upgrade/IBEX_upgrade.py
installation_and_upgrade/instrument_install_latest_build_only.bat

* Add option to specify prefix to directory used to install latest build from
* Allow this option to be specified via   install_latest-build_only.bat
See ISISComputingGroup/IBEX#4604
This is tested as part of FreddieSystemTests and FreddieIocTests jobs
it could be tested on e.g. demo by running the bat script

Allow alternative install source prefix

---

installation_and_upgrade/ibex_install_utils/install_tasks.py

Added a flag to ignore errors when stopping MYSQL service as part of the update to the latest version. This stops the script from falling over when trying to stop MYSQL when it was not running in the first place

Update install tasks

---

installation_and_upgrade/ibex_install_utils/install_tasks.py

Added a step to the deploy / install script with instructions on how to configure IE to use a custom proxy configuration that blocks all traffic, except for selected whitelisted sites.
Ticket: https://github.com/ISISComputingGroup/IBEX/issues/5112

Add instructions for configuring IE.

---

installation_and_upgrade/instrument_deploy.bat

There is an error in the deploy script which means that the automated start of the IBEX server between update and post-deploy system tests does not work properly.
The reason was that python environment variables were set for the install which were overwriting the values set by config_env. These changes confine this assignment to a local context which should fix the issue.

Fix IBEX server start

---

installation_and_upgrade/instrument_deploy.bat

Use local python to run `instrument_deploy_post_start`
Ticket: https://github.com/ISISComputingGroup/IBEX/issues/5254
Acceptance criteria:

Use local python

---

installation_and_upgrade/ibex_install_utils/install_tasks.py

Adds a fix for instruments which cannot start their alarms server. A new upgrade step truncates the alarms table to fix the issue.
https://github.com/ISISComputingGroup/IBEX/issues/4776

Ticket4776 fix alarm database

---

installation_and_upgrade/IBEX_upgrade.py
installation_and_upgrade/ibex_install_utils/install_tasks.py

Fixes issue seen in builds e.g. http://epics-jenkins.isis.rl.ac.uk/view/WallDisplay/job/System_Tests_IOCs/4792/console where there is no default for current version number. This adds in `None` as the default and prints a sensible email format based on that

Fixes email template if version is not known

---

installation_and_upgrade/ibex_install_utils/tasks/python_tasks.py

To test:
* On master run the upgrade script and answer no to everything other than "Update script generator script definitions"
* Confirm script fails with an exception
* Do the same on this branch and confirm it doesn't fail

Fix update script definitions so it doesn't crash

---

installation_and_upgrade/IBEX_upgrade.py
installation_and_upgrade/define_latest_genie_python.bat
installation_and_upgrade/ibex_install_utils/ca_utils.py
installation_and_upgrade/ibex_install_utils/motor_params.py
installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
installation_and_upgrade/instrument_deploy.bat

See https://github.com/ISISComputingGroup/IBEX/issues/5573
Turns out the original issue was caused by the upgrade script trying to run bits of genie_python in python 2. This PR changes those to be run in python 3.
To test do a deploy using `instrument_deploy.bat` and confirm none of the steps fail.

Ticket 5573: Steps that require genie_python are now done in python 3

---

installation_and_upgrade/IBEX_upgrade.py
installation_and_upgrade/ibex_install_utils/file_utils.py
installation_and_upgrade/ibex_install_utils/install_tasks.py
installation_and_upgrade/ibex_install_utils/run_process.py
installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py

See https://github.com/ISISComputingGroup/IBEX/issues/3928
To test:
1. Start your instrument
1. Create the folder `C:\Labview Modules\DAE` and unzip [icp_config.zip](https://github.com/ISISComputingGroup/ibex_utils/files/4912788/icp_config.zip) into it
1. Console into `ISISDAE`, toggle autorestart to off and kill the IOC (keep the console open)
1. In taskmanager kill `ISISICP` and confirm it doesn't restart itself (keep task manager open)
1. Run the upgrade script with `python IBEX_upgrade.py --kits_icp_dir \\isis.cclrc.ac.uk\inst$\Kits$\CompGroup\ICP\ --confirm_step instrument_deploy_main`
1. Reply `N` to the first 6 steps then `Y` to the update ICP step
1. Confirm the script copies from the DAE2 directory
1. After copy (and after you've entered admin credentials for the register) start …

Ticket 3928: Update ICP during deploy

---

installation_and_upgrade/ibex_install_utils/install_tasks.py
installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py

The web dashboard now automatically picks up changes to the instrument list, so these steps are no longer required.
This was demonstrated during the install on INTER, which didn't need these steps but does show on the dashboard

Remove redundant install task

---

build_tools/purge_archive.bat
installation_and_upgrade/developer_update.bat
installation_and_upgrade/instrument_deploy.bat
installation_and_upgrade/instrument_install.bat
installation_and_upgrade/instrument_install_latest_build_only.bat
installation_and_upgrade/instrument_test.bat
installation_and_upgrade/instrument_update.bat
installation_and_upgrade/truncate_database.bat
installation_and_upgrade/upgrade_mysql.bat
installation_and_upgrade/vhd_build.bat

Calls python3 instead of python2 when running the instrument update batch script. Hopefully this should fix the system test builds on Jenkins

Calling py3 on instrument update script

---

installation_and_upgrade/IBEX_upgrade.py
installation_and_upgrade/ibex_install_utils/file_utils.py
installation_and_upgrade/ibex_install_utils/install_tasks.py
installation_and_upgrade/ibex_install_utils/motor_params.py
installation_and_upgrade/ibex_install_utils/run_process.py
installation_and_upgrade/ibex_install_utils/task.py
installation_and_upgrade/ibex_install_utils/tasks/__init__.py
installation_and_upgrade/ibex_install_utils/tasks/backup_tasks.py
installation_and_upgrade/ibex_install_utils/tasks/client_tasks.py
installation_and_upgrade/ibex_install_utils/tasks/mysql_tasks.py
installation_and_upgrade/ibex_install_utils/tasks/python_tasks.py
installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
installation_and_upgrade/ibex_install_utils/tasks/vhd_tasks.py
installation_and_upgrade/vhd_scheduled_task.py

The system tests are currently failing on this step as the imports are absolute from the root of the repo which is not how the scripts are run.

Fix installation and upgrade imports

---

installation_and_upgrade/ibex_install_utils/run_process.py

System tests were failing because of this I think.

Changing string to bytes in run_process call

---

installation_and_upgrade/ibex_install_utils/install_tasks.py
installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py

Add a task for installing the instrument scripts repo and run it as part of install latest. This is because https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/73 adds a squish test for the scans library so the repo needs to be installed on test machines.
For https://github.com/ISISComputingGroup/IBEX/issues/5785

Added task for installing shared scripts repo

---

installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
installation_and_upgrade/ibex_install_utils/tasks/vhd_tasks.py
installation_and_upgrade/vhd_scheduled_task.py

- Fix stray `f` which somehow got added in dismount commands
- Fix looking for wrong python init file (on `NDHSPARE70` should be `init_spare70.py`)
- Fix number of arguments being passed to upgrade script.

Fix VHD build: round 2

---

installation_and_upgrade/ibex_install_utils/install_tasks.py
installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
installation_and_upgrade/ibex_install_utils/tasks/vhd_tasks.py

- Fix control flow
- use `specific_inst_file` everywhere it's needed
- print the output of scheduled task log if error

Fix VHD build: round 3

---

installation_and_upgrade/ibex_install_utils/admin_runner.py

Uses a TemporaryFile instead of a hardcoded bat file, i added a context manager here so we can use it elsewhere if needed. 
See ISISComputingGroup/IBEX#5906
Add
```python
if __name__ == '__main__':
cmd = AdminCommandBuilder()
cmd.run_all()
```
to the end of the script
and a 60 second sleep in the `with temp_bat_file` statement
- check the file exists before it is executed (usually in `C:\Users\username\AppData\Local\Temp`, it will be a randomly-named bat script
- check it is removed thereafter

Ticket5906 temp admin file

---

build_tools/JenkinsfileCheckRecentBuilds
build_tools/check_builds_are_recent.bat
build_tools/check_builds_are_recent.py

I've added a tool in https://github.com/ISISComputingGroup/ibex_utils/pull/119 that runs on Jenkins to check for kits$ for if the client, epics and genie python most recent builds are more than 5 days old. See https://epics-jenkins.isis.rl.ac.uk/view/WallDisplay/job/Stale%20Builds%20Checker/ for it running. When merged we need to change the branch of this checker Jenkins job back to master.

Ticket6575 check stale builds

---

installation_and_upgrade/IBEX_upgrade.py
installation_and_upgrade/ibex_install_utils/install_tasks.py
installation_and_upgrade/ibex_install_utils/tasks/__init__.py
installation_and_upgrade/ibex_install_utils/tasks/backup_tasks.py
installation_and_upgrade/ibex_install_utils/tasks/client_tasks.py
installation_and_upgrade/ibex_install_utils/tasks/common_paths.py
installation_and_upgrade/vhd_post_install.bat

- Changed the ibex client install to reference the new `install_client_with_builtin_python.bat` to remove instances of double installs for external genie python 3 (i.e., Instrument/Apps/Python3)
- Simplified the ibex client install logic by removing references to Client_E4

Ticket 7227 - stop multiple python installs

---

developer_support_script/check_build_stability.py

A quick refactor of the build stability script into a singleton to improve readability.

Refactor Check Build Stability Script

---

ioc_copier/ioc_copier.py
ioc_copier/test_ioc_copier.py

Made changes to ioc copier script so that it can be used on IOC-01 to create IOC-02 and up. Due to there being more edge cases on doing so, added restrictions so that IOCs that are likely to cause problems (No st-common.cmd or use of sequencer) the script will fail. 
And use of asub records within the ioc directory itself will warn the user that they may need to check the C++.
https://github.com/ISISComputingGroup/IBEX/issues/7353

Updated IOC copier to allow creation of IOC 2

---

installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py

https://github.com/ISISComputingGroup/IBEX/issues/7441
Confirmed that GALIL driver selection works as expected and added a secondary prompt if a choice between drivers is given by the deploy script.
The script prompts for a choice if either `GALIL-OLD` or `GALIL-NEW` directory is missing.

Ticket7441

---

installation_and_upgrade/IBEX_upgrade.py

Updated deploy script to handle a 32bit EPICS build.
https://github.com/ISISComputingGroup/IBEX/issues/7384

Ticket7384

---

installation_and_upgrade/IBEX_upgrade.py
installation_and_upgrade/vhd_build.bat
installation_and_upgrade/vhd_build_force_cleanup.bat
installation_and_upgrade/vhd_build_release.bat

As this breaks mounting the `var` VHD

Don't log to var area for VHD builds

---

installation_and_upgrade/ibex_install_utils/tasks/mysql_tasks.py

Don't need to move the resulting file; we are backing up directly to the network

 Don't need to move the resulting file; we are backing up directly to the network

---

installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
installation_and_upgrade/instrument_deploy.bat

- Add parameter to `instrument_deploy.bat` to allow for deploying 32-bit builds.
- Clarify system task `"Record running vis"` into something more coherent.

Add parameter for 32bit deploys and clarify system task name

---

installation_and_upgrade/ibex_install_utils/file_utils.py
installation_and_upgrade/ibex_install_utils/tasks/backup_tasks.py

If top level EPICS is a link, remove contents of directory it is linked to but do not remove the link itself. We use links a lot on build servers, this is to avoid rename issues and links going missing

Do not remove top level directory link

---

installation_and_upgrade/ibex_install_utils/tasks/common_paths.py

Correct path so old client is actually backed up during install

Correct client directory

---

developer_support_script/check_build_stability.py

Refactored the script to make changes easier. Should now ignore all manually aborted builds, and also exclude all aborted builds from any failure calculations.
https://github.com/ISISComputingGroup/IBEX/issues/7841

Ticket7841

---

developer_support_script/check_build_stability.py

The refactored stability check crashed in the scenario of a build failing with no test report (i.e. a failure due to a jenkins error).
This PR fixes that, and also tracks how many such failures occur to keep track of similar to how aborted builds are handled.

Fixed stability check Failing when build failure with no test report

---

installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
installation_and_upgrade/instrument_deploy.bat

Updated Galil version checker to use a copied GALIL_OLD/NEW.txt file that is now copied before it's overwritten by the IBEX server install (within which you decide the Galil version).
**To test I'd advise just adding in `input()` after each of the 3 options in the `server.tasks.py` file so you can cancel the script before it installs IBEX again.**
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/7982)
*Give an overview of unit tests you have added or modified, if applicable. The aim is provide information to help the reviewer*
*Mention any automated tests or manual tests that you have added or modified, if applicable. The aim is provide information to help the reviewer*
*Highlight and provide a link to any additions or changes to the documentation, if applicable. The …

Ticket7982

---

installation_and_upgrade/ibex_install_utils/install_tasks.py

I've looked at the commit history of when this bug was introduced. It was added when copying and pasting the line that calls the server task from the `run_instrument_deploy_pre_stop()` function to the `run_instrument_deploy_post_start()` function. This was not noticed in testing as testing only ran through the deploy script till just past the point of which the new functions I wrote run for the first time, emphasis on **first time.** Which I believe to be why the typo has gone unnoticed.

Removed typo in function call for 'motors, blocks & blockserver' task

---

installation_and_upgrade/ibex_install_utils/tasks/backup_tasks.py

Forward the unused shutil ignore func to the `move_file` function and use the copytree function with the present move function as the copy_function param of the copytree function.

Ticket8186_ignore_list_not_passed_to_move_func

---

installation_and_upgrade/ibex_install_utils/file_utils.py
installation_and_upgrade/ibex_install_utils/tasks/backup_tasks.py

Using copytree to get a dir size meant using a custom copy function again and if we are looping through all the files we may as well count them while we do. Thus, I merged counting the dir's number of files into the function of getting the dir size. Otherwise we'd be looping through all a dir's files twice before actually copying/moving.

Merged counting of files and getting dir size

---

installation_and_upgrade/ibex_install_utils/version_check.py

Running `upgrade_mysql.bat` without this fix should produce a TypeError:
`TypeError: version_check.<locals>._version_check_decorator.<locals>._wrapper() got an unexpected keyword argument 'force'`
Running the same with the changes should produce no error and prompt you to enter admin credentials to commence the update.

Pass positional and keyword arguments through version_check decorator

---

installation_and_upgrade/ibex_install_utils/tasks/__init__.py

To test on developer machine:
- Start backup end of the day
The step that would back up Client_E4 and EPICS_UTILS will fail and pause execution. That is fine.
- Next morning carry on ignoring the Client_E4 and EPICS_UTILS. You will notice the next two folders are still going to be saved into the directory with the date of yesterday.
- Then say Y to verify backup and everything should be good apart from the two missing directories (Client_E4 and EPICS_UTILS)

Cache backup start date

---

.github/workflows/push_event_workflow.yml
installation_and_upgrade/ibex_install_utils/ca_utils.py
installation_and_upgrade/ibex_install_utils/run_process.py
installation_and_upgrade/ibex_install_utils/tasks/__init__.py
installation_and_upgrade/ibex_install_utils/tasks/backup_tasks.py
installation_and_upgrade/ibex_install_utils/tests/test_backup_tasks.py
installation_and_upgrade/ibex_install_utils/tests/test_dummy.py
installation_and_upgrade/ibex_install_utils/tests/test_test.py
installation_and_upgrade/requirements.txt
installation_and_upgrade/run_tests.bat

Created a framework for unit testing & unit tests for a few backup tasks

Ticket 8211 unit test

---

build_tools/check_builds_are_recent.py

https://github.com/ISISComputingGroup/IBEX/issues/8287 for test instructions
Enables differnet builds to be checked for differnt ages of latest build and for this to be configured. This will enable new builds to be added through the Jenikins update without changes to the script
Once merged, jenkins configurationw will need updating to point back at master before the branch is deleted.

Ticket 8287 - Update to stale build checks to paramatise

---

installation_and_upgrade/ibex_install_utils/tasks/mysql_tasks.py

Use `delayed-start` on service, needed on e.g. hifi-cryomag as disk volumes mounted late
though you cannot run the upgrade script, as admin run the command it would run
```
sc config MYSQL80 start= delayed-auto
```
and check your mysql goes in `automatic (delayed start)` in the services display

Make mysql delayed start

---

build_tools/check_builds_are_recent.py
installation_and_upgrade/IBEX_upgrade.py
installation_and_upgrade/ibex_install_utils/tasks/vhd_tasks.py

Removed exsisting checks for folders without '-' as these have been removed
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/8329)
Creation of Builds all follow the same format "BUILD-####"
---

Ticket8329jenkins

---

installation_and_upgrade/ibex_install_utils/install_tasks.py

Fix the system tests as they run: 
(https://github.com/ISISComputingGroup/system_tests/blob/master/Jenkinsfile#L93)
`instrument_install_latest_build_only.bat` 
which in turn uses install_latest 
(https://github.com/ISISComputingGroup/ibex_utils/blob/master/installation_and_upgrade/instrument_install_latest_build_only.bat#L37C18-L37C32)
which then uses `install_latest` in installtasks.py  (https://github.com/ISISComputingGroup/ibex_utils/blob/master/installation_and_upgrade/ibex_install_utils/install_tasks.py#L382) 
which maps to `remove_all_and_install_client_and_server`
https://github.com/ISISComputingGroup/ibex_utils/blob/master/installation_and_upgrade/instrument_install_latest_build_only.bat#L37C18-L37C32

Fix system tests by not setting up log rotation

---

ioc_copier/ioc_copier.py

This fixes the IOC copier thinking that a sequence program is being used when this line is in the st-common.cmd:  ` #seq sncxxx,"user=vux62295"` - notice the prefixed `#`  - i think the device generator puts this in by default, or at least used to. 
to test follow the instructions here https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Shared-utility-scripts#ioc-copier with and without a `seq` line in the st-common.cmd

Fix ioc copier false alarming when #seq is in st-common.cmd

---

build_tools/check_builds_are_recent.bat
build_tools/purge_archive.bat
installation_and_upgrade/define_latest_genie_python.bat
installation_and_upgrade/developer_update.bat
installation_and_upgrade/instrument_deploy.bat
installation_and_upgrade/instrument_install.bat
installation_and_upgrade/instrument_install_latest_build_only.bat
installation_and_upgrade/instrument_save_settings.bat
installation_and_upgrade/instrument_test.bat
installation_and_upgrade/instrument_update.bat
installation_and_upgrade/remove_genie_python.bat
installation_and_upgrade/run_standalone_backup.bat
installation_and_upgrade/save_motor_params.bat
installation_and_upgrade/truncate_database.bat
installation_and_upgrade/upgrade_mysql.bat
installation_and_upgrade/vhd_build.bat
installation_and_upgrade/vhd_build_force_cleanup.bat
installation_and_upgrade/vhd_build_release.bat

- Whenever `define_latest_genie_python.bat` is called, a python build is installed under `%tmp%\Python_Build_xxxx\`, or if a path is passed to define_latest_genie_python then it will install it under that path.
- Creates a new batch file `remove_genie_python.bat` which takes a path of where python is installs- it will uninstall it then undefine the global variables set in  `define_latest_genie_python.bat`.
- Made adjustments to every file referencing  `define_latest_genie_python.bat` so that it calls `remove_genie_python.bat` after the local python build has been used.
This should be merged before any other PR relating to this ticket.

8437 create network independent python venv

---

installation_and_upgrade/define_latest_genie_python.bat
installation_and_upgrade/remove_genie_python.bat

Genie python was not getting installed properly because of a bug merged in https://github.com/ISISComputingGroup/IBEX/issues/8437 . This is fixed by instead calling `%genie_dir%\BUILD-%PYTHON_BUILD_NO%\genie_python_install.bat %LATEST_PYTHON_DIR%` which means that the following 
```
set "LATEST_PYTHON=%LATEST_PYTHON_DIR%\python.exe"
set "LATEST_PYTHON3=%LATEST_PYTHON_DIR%\python3.exe"
```
is executed. Also fixed problem in remote genie python, whereby `path` was being overwritten because of a poorly chosen variable name.

Fixes genie python install variables

---

installation_and_upgrade/define_latest_genie_python.bat

Uses `random` instead of python build number as a directory to install python so that multiple python builds can be installed and used concurrently without permissions issues.

Fixes define genie python

---

release_scripts/Jenkinsfile_branches
release_scripts/branches.py

Rather than the old genie_python repo which is now archived.
Should have been part of https://github.com/ISISComputingGroup/IBEX/issues/8381 as our release process is now releasing the _distribution_ (uktena) half of the split - the library is released separately, to pypi, via other mechanisms noted on release creation page.
I forgot to add these changes as part of that ticket.
`genie_python` version file no longer needs to be written explicitly as it is done by `setuptools_scm` (see https://github.com/ISISComputingGroup/genie/pull/7 for details)

Adjust release-creation scripts to refer to uktena repo for python distribution creation

---

installation_and_upgrade/remove_genie_python.bat

Otherwise directory cannot be totally removed
I tried using `del` with `||` but it never gave correct exit code, hence current exists logic. Can't check errorlevel as inside if and `%` will not work, and can't use `!` as we can't `setlocal EnableDelayedExpansion` due to unsetting of external environment variables  in script

genie uninstall: Kill caRepeater if running

---

installation_and_upgrade/instrument_install_latest_build_only.bat
installation_and_upgrade/update_genie_python_module.bat

Update the local genie python to latest master on a non-release install, this ensure we are testing most recent code  
Needed as https://github.com/ISISComputingGroup/system_tests/blob/0956009a2b255d0dec325701e5e6f320ab11f528/run_tests.bat#L5 just covers python running system tests code and not the ibex server running in the background

Update genie modules on non-release install (primarily for system tests)

---

installation_and_upgrade/ibex_install_utils/tasks/git_tasks.py

This sets the upstream for all branches after an install and pulls before making local instrument branch, this ensures any hotfixes post build of release are immediately installed

Set upstream on all local branches

---

installation_and_upgrade/ibex_install_utils/tasks/backup_tasks.py

Move old backups before doing current backup - this will make space if needed and also avoids needing logic to look at dates and work out which backup should remain

move old backups first

---

.github/workflows/push_event_workflow.yml

Setup python explicitly so that we get 3.11 (like on dev machines), rather than 3.9 which is default-installed on the CI runners if you don't request anything explicitly
I noticed this in https://github.com/ISISComputingGroup/ibex_utils/pull/221 where GHA said we weren't allowed to use `Callable | None`, but this is allowed on 3.11.

Setup python explicitly

---

installation_and_upgrade/instrument_deploy.bat

Start server in new env at end of install to pick up new java path
To test principle used:
from an epics term type
```
start /i /wait cmd /c config_env.bat
```
you'll see test indicating script run
typing instead
```
start /wait cmd /c config_env.bat
```
terminates quickly as env inherited

Start server in new env

---

installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py

`C:\Instrument\Var\logs\schtasks` is created by a recent config_env, if deploying elsewhere will need to manually create that directory

Capture logrotate task output

---

installation_and_upgrade/IBEX_upgrade.py
installation_and_upgrade/instrument_install_latest_build_only.bat

Allow setting of new `--server_winbuild` install argument to specify a win11 build 
See ISISComputingGroup/IBEX#8270
* Enable `System_Tests_Win11_Win11` and `System_Tests_Squish_Win11_Win11` jenkins
* Check jenkins log and confirm that both install `EPICS_CLEAN_win11_x64` builds

Add win11 on win11

---

installation_and_upgrade/remove_genie_python.bat

Remove printing a stray `access denied` message - the delete is only used as a check as to whether to kill the process, so printing the delete failure message is not helpful

Suppress caRepeater delete message

---

build_tools/purge_archive.bat

`e:/Jenkins` was being interpreted as a command switch - need to use `e:\Jenkins`

Fix path to avoid    Invalid switch - Jenkins    error

---

installation_and_upgrade/instrument_install_latest_build_only.bat
installation_and_upgrade/vhd_build.bat
installation_and_upgrade/vhd_build_force_cleanup.bat

previously done by `define_latest_genie_python.bat` which has since been removed.

fix the build by putting kits_icp_path back in where needed

---

installation_and_upgrade/IBEX_upgrade.py
installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
installation_and_upgrade/ibex_install_utils/tasks/vhd_tasks.py
installation_and_upgrade/instrument_install_latest_build_only.bat

Build name had changed and system tests were failing to install ibex. Also fix some `SyntaxWarning: invalid escape sequence '\I'`

Fixes for new jenkins build names

---

installation_and_upgrade/ibex_install_utils/run_process.py
installation_and_upgrade/truncate_database.bat

The default used to be `[0]` (see [here](https://github.com/ISISComputingGroup/ibex_utils/pull/264/files#diff-61e8c4900c83548b08a6ec5b8c3957148b027cc3124526b0fc0ae8e027b291eaL27) ) but was accidentally changed to `[]` (see [here](https://github.com/ISISComputingGroup/ibex_utils/pull/264/files#diff-61e8c4900c83548b08a6ec5b8c3957148b027cc3124526b0fc0ae8e027b291eaR71) )
This can be easily tested by running the `truncate_db` script locally, which uses `RunProcess` - no need to do backup step, just say yes to "truncate" step. Before this PR it'll fail, after it should pass.
Also fixed `truncate_db` script which was trying to use old non-uv way of calling python.

Default `expected_return_code` to `[0]`

---

installation_and_upgrade/ibex_install_utils/install_tasks.py
installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py

Remove restart VIs step
